### ISSUE TITLE
フレームワークの予定について

### ISSUE THREAD

**Issue by taniguchi-ss** [bot-framework/botfw#2]
InCircleとbot-frameworkを現在検証しているのですが、質問があります。

- フレームワークについて、機能追加など今後の開発予定はありますか？

- 現在のhubotの対象バージョンがver.2.19.0を指定されていますが、今後hubotの対象バージョンを上げる予定はありますか？また上記に伴い、フレームワークをcoffee-scriptからjavascriptに変更する予定はありますか？

- InCircleのすべてのAPIには対応していないようですが、今後InCircleの未対応のAPIに対応する予定はありますか？

以上、ご教授いただければ幸いです。

**Comment by botsframework** [comment]
＞フレームワークについて、機能追加など今後の開発予定はありますか？

InCircleのAPI機能追加に従い、開発をしていく予定です。

＞現在のhubotの対象バージョンがver.2.19.0を指定されていますが、今後hubotの対象バージョンを上げる予定はありますか？また上記に伴い、フレームワークをcoffee-scriptからjavascriptに変更する予定はありますか？

我々の認識ではver.2.19.0が最新ですが2年前から更新されていないです。
バージョンアップされたときに必要であれば、バージョンアップをしようと考えています。
また、今のところ、javascriptに変更する予定はありません。

＞InCircleのすべてのAPIには対応していないようですが、今後InCircleの未対応のAPIに対応する予定は＞ありますか？

　必要に応じて、対応する予定ですが、質問者の方で必要と思われるAPI部品はありますか？

**Comment by taniguchi-ss** [comment]
ご回答いただきありがとうございます。

バージョンについてなのですが、
私の認識ですと、hubotの最新バージョンはv3.1.1と思っておりました。
また、バージョンアップの際にcoffee scriptをjavascriptに置き換えているようです。
下記が確認したページです。
https://github.com/hubotio/hubot/commit/7939b8f08a0a4fbbb685cfd67c706ca2d2594002

参照しているページが間違っていますでしょうか？
よろしければ、参照すべきページをご教授いただけると幸いです。


またAPIの部品についてですが、
使用されていないトークルームの閉鎖のために、トークルーム一覧の取得(ticketL,ticketS)や
外部から任意のグループ・任意のユーザに対して、メッセージ送信を行うときに
ユーザ検索(userS)やグループ検索(groupS)を使用する可能性がありそうだなと考えております。
(userLやgroupLを使用してもできるとは思いますが)

**Comment by botsframework** [comment]
hubotの最新バージョンはv.3.1.1ですね。こちらの勉強不足でした。申し訳ございません。
coffeescriptをjavascriptに置き換えていることも確認しました。
ご質問のバージョンアップについてですが、前向きに検討したいと思います。
ただ、変更箇所や影響範囲等の調査に時間がかかるので、少々お時間をいただくと思います。
API部品についても承知しました。こちらも追加を検討したいと思います。
もちろん、ご質問者の方で資産を変更いただき、pull requestしていただいても結構です。

**Comment by taniguchi-ss** [comment]
バージョンアップ対応や機能追加について現在は検討中であると、認識いたしました。
お忙しい中、ご回答ありがとうございます。

また何かありましたら、質問させていただきますので、
その時はどうぞよろしくお願いいたします。
