### ISSUE TITLE
ユーザ情報の取得について

### ISSUE THREAD

**Issue by taniguchi-ss** [bot-framework/botfw#3]
InCircleのAPIについて質問がございます。

ユーザNoからユーザの情報を取得したいのですが、
APIドキュメントを見る限り、そのようなことが実現できるAPIが見つかりません。
(ユーザIDで検索できるAPIはありました)
bot-frameworkではp(イベント情報オブジェクト)にusernoを挿入しているようですが、
このusernoを元にユーザ情報を取得するにはどうしたらいいでしょうか。

よろしければ、ご教授いただけると幸いです。

**Comment by botsframework** [comment]
InCircleAPIには、ユーザNoからユーザ情報を検索できる機能はございません。
userLやAssignLなどでユーザ情報の一覧を取得して※
usernoが一致するユーザを特定する、等の操作をしていただく必要があります。
※botfw/hubot/ic2modules/ic2api/にuserLやAssignLのモジュールを用意しておりますので、それをお使いください。

**Comment by taniguchi-ss** [comment]
ご回答ありがとうございます。
usernoからユーザ情報が取得できない旨、かしこまりました。
記載していただいた手段を検討いたします。

以上
