### ISSUE TITLE
トーク情報の検索について

### ISSUE THREAD

**Issue by taniguchi-ss** [bot-framework/botfw#4]
InCircleのAPIについて質問がございます。

ユーザNoからトークルームの一覧を取得したいのですが、
APIドキュメントに記載のある、ticketSのAPIにてアクション"2"で利用したところ、
トークルームの一覧情報が取得できません。

下記の現象が起きています。
・APIユーザのusernoを条件に設定した場合
→resultはsuccessだが、1件も情報が設定されていない。
・標準ユーザのusernoを条件に設定した場合
→resultがfailureで、err_msgが「アクセスできません」になっている。

どのようにすれば、ユーザNoからトークルームの一覧が取得できますでしょうか。

よろしければ、ご教授いただけると幸いです。

**Comment by botsframework** [comment]
質問者の方はおそらくユーザNoに紐づくルームを全部取得したいと思いますが、APIの仕様としては、APIユーザと指定したユーザが同居しているルームしか検索できないです。
従って、標準ユーザを条件にしても取得できないです。

・APIユーザのusernoを条件に設定した場合
→resultはsuccessだが、1件も情報が設定されていない。

上記についてですが、
考えられるケースとしては下記が考えられます。
・APIユーザが存在するトークがない
・パラメタ設定ミス

例えば、APIユーザとAさん（番号1）のトークがある場合は、
パラメタv7でAPIユーザとAさんのusernoを指定し、実行するとヒットします。APIユーザの番号のみを指定した場合は自分1人のトークという意味あいになるはずなので、0件になっていると思います。

**Comment by taniguchi-ss** [comment]
ご回答ありがとうございます。
仕様について誤解していました。
ユーザNoで検索するには、トーク内の全てのユーザNoを設定する必要があるのですね。

つまり、APIユーザが含まれているトークを探す方法は、
全てのトークルームを検索して(ticketLを使用して)、ユーザが含まれているか確認しなければならない、
ということで合っていますでしょうか？

**Comment by botsframework** [comment]
APIユーザが含まれているトークを探す方法はticketLを使えば良いです。
ただ、トークにどのユーザが含まれているのかAssignLで確認しないと分からないです。

**Comment by taniguchi-ss** [comment]
仕様についてかしこまりました。ご回答ありがとうございます。
